name: Build and release

on:
  push:
    # branches:
    #   - master
    paths-ignore:
      - 'docs/**'

jobs:
  node:
    name: Node 12
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync packages with cache
        uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node_modules-

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Build the docs
        run: yarn document

      - name: Compile src
        run: yarn build

      - name: Commit docs
        uses: EndBug/add-and-commit@v4
        with:
          add: 'docs'
          author_name: Github Workflow Bot
          author_email: bot@github.com
          message: 'build docs'
        env:
          GITHUB_TOKEN: ${{ github.token }}
