name: Test and lint

on: [push]

jobs:
  node:
    name: Node 12
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync packages with cache
        uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node_modules-

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        run: yarn lint --quiet --color

      - name: Run tests
        id: tests
        run: yarn run test --watchAll=false --colors --ci --coverage

      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v1
